---
- name: Add specified users to privileged systemd-journal group
  become: true
  user:
    name: "{{ item }}"
    groups: "{{ journal_group }}"
    append: yes
  loop: "{{ journal_group_adds }}"
  tags:
    - systemd-journal-group
